language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
    - sudo apt-get update > /dev/null
    - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl
    - sudo sed -i -e "/DocumentRoot/i\ServerName szachuje.dev" /etc/apache2/sites-available/default
    - echo "127.0.0.1 szachuje.dev" | sudo tee -a /etc/hosts
    - sudo /etc/init.d/apache2 restart
    - composer install -n
    - chmod -R 777 app/cache app/logs
    - app/console --env=test cache:warmup
    - chmod -R 777 app/cache app/logs
    - sh -e /etc/init.d/xvfb start
    - export DISPLAY=:99.0
    - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.35.0.jar
    - java -jar selenium-server-standalone-2.35.0.jar > /dev/null &
    - sleep 5

script:
  - bin/behat --no-snippets --no-paths --verbose
  - bin/behat -p mobile --no-snippets --no-paths --verbose
  - bin/phpspec run -fpretty --verbose
