szachuje_training:
    resource: "@SzachujeWebBundle/Controller/"
    type:     annotation
    prefix:   /

szachuje_web:
    resource: "@SzachujeWebBundle/Resources/config/routing.yml"
    prefix: /
